### Create a url ###
POST http://localhost:3000/urls/
Content-Type: application/json

{
    "url": "https://google.cl"
}

### Get by sufix ###
GET http://localhost:3000/urls/ii6X

### Simulate click ###
PATCH http://localhost:3000/urls/ii6X/click


### Delete by id ###
DELETE http://localhost:3000/urls/67e94f4740ae04b88776ae18 