### Create a url ###
POST http://localhost:3000/api/urls/
Content-Type: application/json

{
    "url": "https://youtube.cl"
}

### Get by sufix ###
GET http://localhost:3000/api/urls/HbpWr1WE

### Simulate click ###
PATCH http://localhost:3000/api/urls/HbpWr1WE/clicks


### Delete by id ###
DELETE http://localhost:3000/api/urls/67e94f4740ae04b88776ae18 

### Check if exist ###
GET http://localhost:3000/api/urls/HbpWr1WE/exist